services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: learning_path_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d learning_path_db"]
      interval: 30s
      retries: 3
      timeout: 20s
      start_period: 10s
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  web:
    build: .
    command: >
      sh -c "
             python manage.py makemigrations &&
             python manage.py migrate &&
             
             
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DEBUG: "True"
      DB_NAME: learning_path_db
      DB_USER: username
      DB_PASSWORD: yourpassword
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
volumes:
  postgres_data:
  redis_data: