services:
  
  web:
    build: .
    dns:
      - 8.8.8.8
      - 1.1.1.1 
    command: >
      sh -c "
             python manage.py makemigrations &&
             python manage.py migrate &&
             
             
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    
    environment:
      DEBUG: "True"
      DB_NAME: learning_path_db
      DB_USER: username
      DB_PASSWORD: yourpassword
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
