# Generated by Django 5.2 on 2025-05-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningpath',
            name='institution',
        ),
    ]
