# Generated by Django 5.2 on 2025-05-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_remove_learningpath_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
