# Generated by Django 5.2 on 2025-05-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_lecture_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='certificate_url',
            field=models.URLField(default=''),
        ),
    ]
