# Generated by Django 5.2 on 2025-06-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_assessment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpathprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningpathprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
